FROM quay.io/centos-bootc/centos-bootc:stream9
COPY usr usr
COPY *.repo /etc/yum.repos.d/
RUN dnf --disablerepo='*' --enablerepo=copr-coreos-continuous --enablerepo=copr-rhcontainerbot-bootc -y distro-sync && \
    dnf clean all
# Note we need to regenerate the initramfs because ostree is included in it
RUN set -x; kver=$(cd /usr/lib/modules && echo *); dracut -vf /usr/lib/modules/$kver/initramfs.img $kver
