FROM quay.io/centos-boot/fedora-tier-1:eln@sha256:4693953634fc2c3bff8d53a5f81a4682ac1aeb53b8184703273eef320eda66ef
COPY *.repo /etc/yum.repos.d/
RUN dnf --disablerepo='*' --enablerepo=copr-coreos-continuous --enablerepo=copr-rhcontainerbot-bootc -y distro-sync && \
    dnf clean all && rm -rf /var/* && \
    ostree container commit
