FROM quay.io/centos-boot/fedora-tier-1:eln
COPY *.repo /etc/yum.repos.d/
RUN dnf --disablerepo='*' --enablerepo=copr-coreos-continuous --enablerepo=copr-rhcontainerbot-bootc -y distro-sync && \
    dnf clean all && rm -rf /var/* && \
    ostree container commit
