FROM quay.io/centos-boot/fedora-tier-1:eln@sha256:52dd1a519a9b67ff141827375cd7cec6b51eff8725934ee19700a5725c2b2f9a
COPY *.repo /etc/yum.repos.d/
RUN dnf --disablerepo='*' --enablerepo=copr-coreos-continuous --enablerepo=copr-rhcontainerbot-bootc -y distro-sync && \
    dnf clean all && rm -rf /var/* && \
    ostree container commit
